/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalProject;

import java.awt.Color;
import java.io.FileWriter;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author nutkamonphunturat
 */
public class AddInfo extends javax.swing.JDialog {
    private Infomation infomation;
    private String Sex;
    private static final DecimalFormat df = new DecimalFormat("0.00");
    private int Fat;

    
    /**
     * Creates new form AddInfo
     */
    public AddInfo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
    }
    
    public void showAdd() {
        inAge.setText("");
        inWeight.setText("");
        inHeight.setText("");
        inFrequency.setText("");
        setVisible(true);
    }
    
    public Infomation getInfomation() {
        return infomation;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butShowFrequencyInfo = new javax.swing.JLabel();
        txtFrequency = new javax.swing.JLabel();
        but18to25 = new javax.swing.JButton();
        txtAge = new javax.swing.JLabel();
        but14to17 = new javax.swing.JButton();
        inWeight = new javax.swing.JTextField();
        but6to13 = new javax.swing.JButton();
        inHeight = new javax.swing.JTextField();
        inFrequency = new javax.swing.JTextField();
        but2to5 = new javax.swing.JButton();
        butDone = new javax.swing.JButton();
        inAge = new javax.swing.JTextField();
        butClose = new javax.swing.JLabel();
        txtFat = new javax.swing.JLabel();
        butMale = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        butFemale = new javax.swing.JButton();
        txtWeight = new javax.swing.JLabel();
        butMore25 = new javax.swing.JButton();
        txtHeight = new javax.swing.JLabel();
        frequencyShowPanel = new javax.swing.JPanel();
        FrequencyInfo = new javax.swing.JLabel();
        fatShowPanel = new javax.swing.JPanel();
        FatShow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(248, 244, 255));
        setUndecorated(true);

        butShowFrequencyInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/info.png"))); // NOI18N
        butShowFrequencyInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butShowFrequencyInfoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butShowFrequencyInfoMouseEntered(evt);
            }
        });

        txtFrequency.setFont(new java.awt.Font("FC Friday", 0, 13)); // NOI18N
        txtFrequency.setText("Frequency (1 - 5)");

        but18to25.setBackground(new java.awt.Color(125, 161, 183));
        but18to25.setFont(new java.awt.Font("FC Friday", 0, 12)); // NOI18N
        but18to25.setForeground(new java.awt.Color(255, 255, 255));
        but18to25.setText("18-25");
        but18to25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but18to25ActionPerformed(evt);
            }
        });

        txtAge.setFont(new java.awt.Font("FC Friday", 0, 13)); // NOI18N
        txtAge.setText("Age");

        but14to17.setBackground(new java.awt.Color(125, 161, 183));
        but14to17.setFont(new java.awt.Font("FC Friday", 0, 12)); // NOI18N
        but14to17.setForeground(new java.awt.Color(255, 255, 255));
        but14to17.setText("14-17");
        but14to17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but14to17ActionPerformed(evt);
            }
        });

        inWeight.setBackground(new java.awt.Color(238, 243, 246));
        inWeight.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        inWeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inWeight.setBorder(null);

        but6to13.setBackground(new java.awt.Color(125, 161, 183));
        but6to13.setFont(new java.awt.Font("FC Friday", 0, 12)); // NOI18N
        but6to13.setForeground(new java.awt.Color(255, 255, 255));
        but6to13.setText("6-13");
        but6to13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but6to13ActionPerformed(evt);
            }
        });

        inHeight.setBackground(new java.awt.Color(238, 243, 246));
        inHeight.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        inHeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inHeight.setBorder(null);

        inFrequency.setBackground(new java.awt.Color(238, 243, 246));
        inFrequency.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        inFrequency.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inFrequency.setBorder(null);

        but2to5.setBackground(new java.awt.Color(125, 161, 183));
        but2to5.setFont(new java.awt.Font("FC Friday", 0, 12)); // NOI18N
        but2to5.setForeground(new java.awt.Color(255, 255, 255));
        but2to5.setText("2-5");
        but2to5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2to5ActionPerformed(evt);
            }
        });

        butDone.setBackground(new java.awt.Color(0, 117, 243));
        butDone.setFont(new java.awt.Font("FC Friday", 0, 14)); // NOI18N
        butDone.setForeground(new java.awt.Color(255, 255, 255));
        butDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButDone.png"))); // NOI18N
        butDone.setBorderPainted(false);
        butDone.setContentAreaFilled(false);
        butDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butDoneMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butDoneMouseEntered(evt);
            }
        });
        butDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDoneActionPerformed(evt);
            }
        });

        inAge.setBackground(new java.awt.Color(238, 243, 246));
        inAge.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        inAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inAge.setBorder(null);

        butClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButClose.png"))); // NOI18N
        butClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butCloseMouseEntered(evt);
            }
        });

        txtFat.setFont(new java.awt.Font("FC Friday", 0, 13)); // NOI18N
        txtFat.setText("Fat");

        butMale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButMale.png"))); // NOI18N
        butMale.setBorderPainted(false);
        butMale.setContentAreaFilled(false);
        butMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMaleActionPerformed(evt);
            }
        });

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/BMR.png"))); // NOI18N

        butFemale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButFemale.png"))); // NOI18N
        butFemale.setBorderPainted(false);
        butFemale.setContentAreaFilled(false);
        butFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFemaleActionPerformed(evt);
            }
        });

        txtWeight.setFont(new java.awt.Font("FC Friday", 0, 13)); // NOI18N
        txtWeight.setText("Weight (Kg)");

        butMore25.setBackground(new java.awt.Color(125, 161, 183));
        butMore25.setFont(new java.awt.Font("FC Friday", 0, 12)); // NOI18N
        butMore25.setForeground(new java.awt.Color(255, 255, 255));
        butMore25.setText(">25");
        butMore25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMore25ActionPerformed(evt);
            }
        });

        txtHeight.setFont(new java.awt.Font("FC Friday", 0, 13)); // NOI18N
        txtHeight.setText("Height (Cm)");

        frequencyShowPanel.setOpaque(false);
        frequencyShowPanel.setLayout(null);
        frequencyShowPanel.add(FrequencyInfo);
        FrequencyInfo.setBounds(0, 0, 110, 170);

        fatShowPanel.setOpaque(false);

        javax.swing.GroupLayout fatShowPanelLayout = new javax.swing.GroupLayout(fatShowPanel);
        fatShowPanel.setLayout(fatShowPanelLayout);
        fatShowPanelLayout.setHorizontalGroup(
            fatShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fatShowPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FatShow, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fatShowPanelLayout.setVerticalGroup(
            fatShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fatShowPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FatShow, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        frequencyShowPanel.add(fatShowPanel);
        fatShowPanel.setBounds(0, 0, 110, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inAge, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(txtHeight))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(inWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(inHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtFrequency)
                                    .addGap(5, 5, 5)
                                    .addComponent(butShowFrequencyInfo))
                                .addComponent(txtFat)
                                .addComponent(inFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(frequencyShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(butMore25, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(but18to25, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(but14to17, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(but6to13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(but2to5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butMale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(butFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(butDone, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butClose)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(butClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(Logo)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAge)
                        .addGap(6, 6, 6)
                        .addComponent(inAge, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWeight)
                            .addComponent(txtHeight))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFrequency)
                            .addComponent(butShowFrequencyInfo))
                        .addGap(4, 4, 4)
                        .addComponent(inFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtFat))
                    .addComponent(frequencyShowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butMore25)
                    .addComponent(but18to25)
                    .addComponent(but14to17)
                    .addComponent(but6to13)
                    .addComponent(but2to5))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butMale, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(butDone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMaleActionPerformed
        Sex = "Male";
        if (butMale.isEnabled()) {
            ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butMale.png"));
            butMale.setIcon(Pic);
            ImageIcon Pic1 = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButFemale.png"));
            butFemale.setIcon(Pic1);
        }
    }//GEN-LAST:event_butMaleActionPerformed

    private void butFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFemaleActionPerformed
        Sex = "Female";
        if (butFemale.isEnabled()) {
            ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butFemale.png"));
            butFemale.setIcon(Pic);
            ImageIcon Pic1 = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButMale.png"));
            butMale.setIcon(Pic1);
        }
    }//GEN-LAST:event_butFemaleActionPerformed

    private void butDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDoneActionPerformed
        if (inAge.getText().equals("")) {
            int result = JOptionPane.showConfirmDialog(this, "Please fill out the infomation!", "ERROR", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                return;
            }
        }
        if (inWeight.getText().equals("")) {
            int result = JOptionPane.showConfirmDialog(this, "Please fill out the infomation!", "ERROR", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                return;
            }
        }
        if (inHeight.getText().equals("")) {
            int result = JOptionPane.showConfirmDialog(this, "Please fill out the infomation!", "ERROR", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                return;
            }
        }
        if (inFrequency.getText().equals("")) {
            int result = JOptionPane.showConfirmDialog(this, "Please fill out the infomation!", "ERROR", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                return;
            }
        }
        if (Fat == 0) {
            int result = JOptionPane.showConfirmDialog(this, "Please fill out the infomation!", "ERROR", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                return;
            }
        }
        if (Sex == null) {
            int result = JOptionPane.showConfirmDialog(this, "Please fill out the infomation!", "ERROR", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                return;
            }
        }
        
        LocalDate myTime = LocalDate.now();
        String myFormatTime = myTime.format(DateTimeFormatter.ofPattern("dd-MM-yy"));
        double Weight = Double.parseDouble(inWeight.getText());
        double Height = Double.parseDouble(inHeight.getText());
        double Age = Double.parseDouble(inWeight.getText());
        double inFre = Double.parseDouble(inFrequency.getText());
        double BMR = 0;
        double TDEE = 0;
        
            if (Sex.equals("Male")) {
                BMR = 66.0 + (13.7 * Weight) + (5.0 * Height) - (6.8 * Age);
                    if (inFre == 1) {
                        TDEE += BMR * 1.2;
                    }
                    else if (inFre == 2) {
                        TDEE += BMR * 1.375;
                    }
                    else if (inFre == 3) {
                        TDEE += BMR * 1.55;
                    }
                    else if (inFre == 4) {
                        TDEE += BMR * 1.725;
                    }
                    else if (inFre == 5) {
                        TDEE += BMR * 1.9;
                    }
            }
            else {
                BMR = 665 + (9.6 * Weight) + (1.8 * Height) - (4.7 * Age);
                    if (inFre == 1) {
                        TDEE += BMR * 1.2;
                    }
                    else if (inFre == 2) {
                        TDEE += BMR * 1.375;
                    }
                    else if (inFre == 3) {
                        TDEE += BMR * 1.55;
                    }
                    else if (inFre == 4) {
                        TDEE += BMR * 1.725;
                    }
                    else if (inFre == 5) {
                        TDEE += BMR * 1.9;
                    }
            }
            
            NumberFormat formatter = new DecimalFormat("#0.00");
            BMR = Double.parseDouble(formatter.format(BMR));
            TDEE = Double.parseDouble(formatter.format(TDEE));
            infomation = new Infomation (myFormatTime, Person.username, Sex, Integer.parseInt(inAge.getText()), Integer.parseInt(inWeight.getText()), Integer.parseInt(inHeight.getText()), Integer.parseInt(inFrequency.getText()), Fat, BMR, TDEE);
        
        this.dispose();
        HomeGui.Home.setVisible(true);
        HomeGui.SignIn.setVisible(false);
        HomeGui.UserLogo.setVisible(true);
    }//GEN-LAST:event_butDoneActionPerformed

    private void butMore25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMore25ActionPerformed
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butMore25.png"));
        FatShow.setIcon(Pic);
        Fat = 0;
        Fat += 30;
    }//GEN-LAST:event_butMore25ActionPerformed

    private void but18to25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but18to25ActionPerformed
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/but18to25.png"));
        FatShow.setIcon(Pic);
        Fat = 0;
        Fat += 22;
    }//GEN-LAST:event_but18to25ActionPerformed

    private void but14to17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but14to17ActionPerformed
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/but14to17.png"));
        FatShow.setIcon(Pic);
        Fat = 0;
        Fat += 16;
    }//GEN-LAST:event_but14to17ActionPerformed

    private void but6to13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but6to13ActionPerformed
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/but6to13.png"));
        FatShow.setIcon(Pic);
        Fat = 0;
        Fat += 10;
    }//GEN-LAST:event_but6to13ActionPerformed

    private void but2to5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2to5ActionPerformed
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/but2to5.png"));
        FatShow.setIcon(Pic);
        Fat = 0;
        Fat += 4;
    }//GEN-LAST:event_but2to5ActionPerformed

    private void butCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_butCloseMouseClicked

    private void butCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButClose.png"));
        butClose.setIcon(Pic);
    }//GEN-LAST:event_butCloseMouseExited

    private void butCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butClose.png"));
        butClose.setIcon(Pic);
    }//GEN-LAST:event_butCloseMouseEntered

    private void butDoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butDoneMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butDone.png"));
        butDone.setIcon(Pic);
    }//GEN-LAST:event_butDoneMouseEntered

    private void butDoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butDoneMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButDone.png"));
        butDone.setIcon(Pic);
    }//GEN-LAST:event_butDoneMouseExited

    private void butShowFrequencyInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butShowFrequencyInfoMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/FrequencyInfo.png"));
        FrequencyInfo.setIcon(Pic);
    }//GEN-LAST:event_butShowFrequencyInfoMouseEntered

    private void butShowFrequencyInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butShowFrequencyInfoMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankinfo.png"));
        FrequencyInfo.setIcon(Pic);
    }//GEN-LAST:event_butShowFrequencyInfoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddInfo dialog = new AddInfo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FatShow;
    private javax.swing.JLabel FrequencyInfo;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton but14to17;
    private javax.swing.JButton but18to25;
    private javax.swing.JButton but2to5;
    private javax.swing.JButton but6to13;
    private javax.swing.JLabel butClose;
    private javax.swing.JButton butDone;
    private javax.swing.JButton butFemale;
    private javax.swing.JButton butMale;
    private javax.swing.JButton butMore25;
    private javax.swing.JLabel butShowFrequencyInfo;
    private javax.swing.JPanel fatShowPanel;
    private javax.swing.JPanel frequencyShowPanel;
    private javax.swing.JTextField inAge;
    private javax.swing.JTextField inFrequency;
    private javax.swing.JTextField inHeight;
    private javax.swing.JTextField inWeight;
    private javax.swing.JLabel txtAge;
    private javax.swing.JLabel txtFat;
    private javax.swing.JLabel txtFrequency;
    private javax.swing.JLabel txtHeight;
    private javax.swing.JLabel txtWeight;
    // End of variables declaration//GEN-END:variables
}
