/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalProject;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.Writer;
import java.util.Formatter;
import java.util.Scanner;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nutkamonphunturat
 */
public class HomeGui extends javax.swing.JFrame {

    private static final String FILE_NAME = "/Users/nutkamonphunturat/Documents/PSU/Object Oreinted Programming/OOP/src/FinalProject/TextFile/User Infomation.txt";
    private DefaultTableModel dtm;

    public static HomeGui Home;
    public static JPanel BG;
    public static JButton SignIn;
    public static JButton SignUp;
    public static JButton AddInfo;
    public static JButton ShowProducts;
    public static JButton butLogOut;
    public static JLabel ShowUsername;
    public static JLabel UserLogo;
    public static String Name;
    public static boolean LoginChecker;

    /**
     * Creates new form HomeGui
     */
    public HomeGui() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);

        usershowBGPanel.setVisible(false);
        userLogo.setVisible(false);
        butLogout.setVisible(false);

        this.SignIn = butSignin;
        this.SignUp = butSignup;
        this.UserLogo = userLogo;
        this.butLogOut = butLogout;
        this.Home = this;
        this.Name = Name;
        this.BG = usershowBGPanel;
        this.AddInfo = butAddInfo;
        this.ShowProducts = butShowProducts;

        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) showInfomationTable.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);

        File file = new File(FILE_NAME);
        if (!file.exists()) {
            return;
        }

        try {
            dtm = (DefaultTableModel) showInfomationTable.getModel();
            Scanner sc = new Scanner(file);
            while (sc.hasNextLine()) {
                String line = sc.nextLine().trim();
                if (line != null && !line.equals("")) {
                    String[] row = line.split(",");
                    dtm.addRow(row);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        showInfomationTable.setAutoCreateRowSorter(true);
        showInfomationTable.getRowSorter().toggleSortOrder(0);

        showInfomationTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                boolean selected = showInfomationTable.getSelectedRow() != -1;
                butRemove.setEnabled(selected);
            }
        });
    }

    public int toModelRow(int viewRow) {
        return showInfomationTable.getRowSorter().convertRowIndexToModel(viewRow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showInfomationTable = new javax.swing.JTable();
        butShowProducts = new javax.swing.JButton();
        butRemove = new javax.swing.JButton();
        butClose = new javax.swing.JLabel();
        butMinimize = new javax.swing.JLabel();
        userLogo = new javax.swing.JLabel();
        butAddInfo = new javax.swing.JButton();
        usershowPanel = new javax.swing.JPanel();
        usernameShow = new javax.swing.JLabel();
        usershowBGPanel = new javax.swing.JPanel();
        usernameBG = new javax.swing.JLabel();
        butLoginPanel = new javax.swing.JPanel();
        butSignup = new javax.swing.JButton();
        butSignin = new javax.swing.JButton();
        butLogoutPanel = new javax.swing.JPanel();
        butLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("frame"); // NOI18N
        setUndecorated(true);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/BMR.png"))); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(238, 243, 246));
        jScrollPane1.setOpaque(false);

        showInfomationTable.setFont(new java.awt.Font("FC Friday", 0, 11)); // NOI18N
        showInfomationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Name", "Sex", "Age", "Weight", "Height", "Frequency", "% Fat", "BMR", "TDEE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showInfomationTable.setGridColor(new java.awt.Color(238, 243, 246));
        showInfomationTable.setSelectionBackground(new java.awt.Color(125, 160, 182));
        jScrollPane1.setViewportView(showInfomationTable);

        butShowProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButBuySupplement.png"))); // NOI18N
        butShowProducts.setBorderPainted(false);
        butShowProducts.setContentAreaFilled(false);
        butShowProducts.setEnabled(false);
        butShowProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butShowProductsMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butShowProductsMouseEntered(evt);
            }
        });
        butShowProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butShowProductsActionPerformed(evt);
            }
        });

        butRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButRemove.png"))); // NOI18N
        butRemove.setBorderPainted(false);
        butRemove.setContentAreaFilled(false);
        butRemove.setEnabled(false);
        butRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butRemoveMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butRemoveMouseEntered(evt);
            }
        });
        butRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRemoveActionPerformed(evt);
            }
        });

        butClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButClose.png"))); // NOI18N
        butClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butCloseMouseEntered(evt);
            }
        });

        butMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButMinimize.png"))); // NOI18N
        butMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butMinimizeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butMinimizeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butMinimizeMouseEntered(evt);
            }
        });

        userLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/user16px.png"))); // NOI18N

        butAddInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButAddInfomation.png"))); // NOI18N
        butAddInfo.setBorderPainted(false);
        butAddInfo.setContentAreaFilled(false);
        butAddInfo.setEnabled(false);
        butAddInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butAddInfoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butAddInfoMouseEntered(evt);
            }
        });
        butAddInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddInfoActionPerformed(evt);
            }
        });

        usershowPanel.setOpaque(false);
        usershowPanel.setPreferredSize(new java.awt.Dimension(94, 16));
        usershowPanel.setLayout(null);

        usernameShow.setBackground(new java.awt.Color(255, 255, 255));
        usernameShow.setFont(new java.awt.Font("FC Friday", 0, 14)); // NOI18N
        usernameShow.setForeground(new java.awt.Color(123, 160, 183));
        usernameShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameShow.setToolTipText("");
        usernameShow.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        usernameShow.setPreferredSize(new java.awt.Dimension(94, 16));
        usershowPanel.add(usernameShow);
        usernameShow.setBounds(3, 0, 90, 16);

        usershowBGPanel.setOpaque(false);
        usershowBGPanel.setPreferredSize(new java.awt.Dimension(94, 16));

        usernameBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/showBG.png"))); // NOI18N
        usernameBG.setLabelFor(usernameShow);

        javax.swing.GroupLayout usershowBGPanelLayout = new javax.swing.GroupLayout(usershowBGPanel);
        usershowBGPanel.setLayout(usershowBGPanelLayout);
        usershowBGPanelLayout.setHorizontalGroup(
            usershowBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernameBG)
        );
        usershowBGPanelLayout.setVerticalGroup(
            usershowBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernameBG)
        );

        usershowPanel.add(usershowBGPanel);
        usershowBGPanel.setBounds(0, 0, 94, 16);

        butLoginPanel.setOpaque(false);
        butLoginPanel.setLayout(null);

        butSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButSignup.png"))); // NOI18N
        butSignup.setBorderPainted(false);
        butSignup.setContentAreaFilled(false);
        butSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butSignupMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butSignupMouseEntered(evt);
            }
        });
        butSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSignupActionPerformed(evt);
            }
        });
        butLoginPanel.add(butSignup);
        butSignup.setBounds(0, 0, 74, 16);

        butSignin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButSignin.png"))); // NOI18N
        butSignin.setBorderPainted(false);
        butSignin.setContentAreaFilled(false);
        butSignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butSigninMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butSigninMouseEntered(evt);
            }
        });
        butSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSigninActionPerformed(evt);
            }
        });
        butLoginPanel.add(butSignin);
        butSignin.setBounds(80, 0, 73, 16);

        butLogoutPanel.setOpaque(false);

        butLogout.setBackground(new java.awt.Color(255, 255, 255));
        butLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButLogout.png"))); // NOI18N
        butLogout.setBorderPainted(false);
        butLogout.setContentAreaFilled(false);
        butLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butLogoutMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butLogoutMouseEntered(evt);
            }
        });
        butLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout butLogoutPanelLayout = new javax.swing.GroupLayout(butLogoutPanel);
        butLogoutPanel.setLayout(butLogoutPanelLayout);
        butLogoutPanelLayout.setHorizontalGroup(
            butLogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(butLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        butLogoutPanelLayout.setVerticalGroup(
            butLogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(butLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        butLoginPanel.add(butLogoutPanel);
        butLogoutPanel.setBounds(80, 0, 73, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(butLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butMinimize)
                        .addGap(6, 6, 6)
                        .addComponent(butClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userLogo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(usershowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(butShowProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(butRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Logo)
                                .addGap(355, 355, 355)
                                .addComponent(butAddInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(butMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(butLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butAddInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butShowProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(usershowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseClicked
        Formatter outFile = null;

        try {
            outFile = new Formatter(FILE_NAME);
            for (int row = 0; row < showInfomationTable.getRowCount(); row++) {
                outFile.format("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n",
                        dtm.getValueAt(row, 0),
                        dtm.getValueAt(row, 1),
                        dtm.getValueAt(row, 2),
                        dtm.getValueAt(row, 3),
                        dtm.getValueAt(row, 4),
                        dtm.getValueAt(row, 5),
                        dtm.getValueAt(row, 6),
                        dtm.getValueAt(row, 7),
                        dtm.getValueAt(row, 8),
                        dtm.getValueAt(row, 9));
            }

        } catch (Exception e) {
            e.printStackTrace();
            return;
        } finally {
            if (outFile != null) {
                outFile.close();
            }
        }
        System.exit(0);
    }//GEN-LAST:event_butCloseMouseClicked

    private void butCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butClose.png"));
        butClose.setIcon(Pic);
    }//GEN-LAST:event_butCloseMouseEntered

    private void butCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButClose.png"));
        butClose.setIcon(Pic);
    }//GEN-LAST:event_butCloseMouseExited

    private void butMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_butMinimizeMouseClicked

    private void butMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butMinimizeMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butMinimize.png"));
        butMinimize.setIcon(Pic);
    }//GEN-LAST:event_butMinimizeMouseEntered

    private void butMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butMinimizeMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButMinimize.png"));
        butMinimize.setIcon(Pic);
    }//GEN-LAST:event_butMinimizeMouseExited

    private void butRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRemoveActionPerformed
        int row = toModelRow(showInfomationTable.getSelectedRow());
        dtm.removeRow(row);
    }//GEN-LAST:event_butRemoveActionPerformed

    private void butRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butRemoveMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butRemove.png"));
        butRemove.setIcon(Pic);
    }//GEN-LAST:event_butRemoveMouseEntered

    private void butRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butRemoveMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButRemove.png"));
        butRemove.setIcon(Pic);
    }//GEN-LAST:event_butRemoveMouseExited

    private void butShowProductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butShowProductsMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butBuySupplement.png"));
        butShowProducts.setIcon(Pic);
    }//GEN-LAST:event_butShowProductsMouseEntered

    private void butShowProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butShowProductsMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButBuySupplement.png"));
        butShowProducts.setIcon(Pic);
    }//GEN-LAST:event_butShowProductsMouseExited

    private void butShowProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butShowProductsActionPerformed
        Formatter outFile = null;

        try {
            outFile = new Formatter(FILE_NAME);
            for (int row = 0; row < showInfomationTable.getRowCount(); row++) {
                outFile.format("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n",
                        dtm.getValueAt(row, 0),
                        dtm.getValueAt(row, 1),
                        dtm.getValueAt(row, 2),
                        dtm.getValueAt(row, 3),
                        dtm.getValueAt(row, 4),
                        dtm.getValueAt(row, 5),
                        dtm.getValueAt(row, 6),
                        dtm.getValueAt(row, 7),
                        dtm.getValueAt(row, 8),
                        dtm.getValueAt(row, 9));
            }

        } catch (Exception e) {
            e.printStackTrace();
            return;
        } finally {
            if (outFile != null) {
                outFile.close();
            }
        }
        
        this.setVisible(false);
        showProduct sp = new showProduct(this, true);
        sp.setVisible(true);
    }//GEN-LAST:event_butShowProductsActionPerformed

    private void butSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSigninActionPerformed
        try {
            String Filepath = "/Users/nutkamonphunturat/Documents/PSU/Object Oreinted Programming/OOP/src/FinalProject/TextFile/Registation.txt";

            FileReader fr = new FileReader(Filepath);
            BufferedReader br = new BufferedReader(fr);
            String line, user, pass;
            boolean isLoginSuccess = false;
            while ((line = br.readLine()) == null) {
                int result = JOptionPane.showConfirmDialog(this, "There is no registation! Please Sign up first.", "Error", JOptionPane.OK_CANCEL_OPTION);
                if (result == JOptionPane.OK_OPTION) {
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        this.setVisible(false);
        LogGui Ldialog = new LogGui(this, true);
        Ldialog.showAdd();
        Person p = Ldialog.getPerson();
        
        try {
            usernameShow.setText(p.username.toUpperCase());
            Name = p.username.toUpperCase();
            LoginChecker = true;
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_butSigninActionPerformed

    private void butSigninMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butSigninMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butSignin.png"));
        butSignin.setIcon(Pic);
    }//GEN-LAST:event_butSigninMouseEntered

    private void butSigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butSigninMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButSignin.png"));
        butSignin.setIcon(Pic);
    }//GEN-LAST:event_butSigninMouseExited

    private void butAddInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddInfoActionPerformed
        AddInfo Adddialog = new AddInfo(this, true);
        this.setVisible(false);
        Adddialog.showAdd();
        Infomation info = Adddialog.getInfomation();
        if (info != null) {
            dtm.addRow(info.toArray());
        }
    }//GEN-LAST:event_butAddInfoActionPerformed

    private void butAddInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butAddInfoMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butAddInfomation.png"));
        butAddInfo.setIcon(Pic);
    }//GEN-LAST:event_butAddInfoMouseEntered

    private void butAddInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butAddInfoMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButAddInfomation.png"));
        butAddInfo.setIcon(Pic);
    }//GEN-LAST:event_butAddInfoMouseExited

    private void butSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSignupActionPerformed
        this.setVisible(false);
        RegGui Rdialog = new RegGui(this, true);
        Rdialog.showAdd();
        Person r = Rdialog.getPerson();

        String FilePath = "/Users/nutkamonphunturat/Documents/PSU/Object Oreinted Programming/OOP/src/FinalProject/TextFile/Registation.txt";
        if (r != null) {
            try {
                LoginChecker = false;
                usernameShow.setText(r.username.toUpperCase());
                Name = r.username.toUpperCase();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_butSignupActionPerformed

    private void butSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butSignupMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butSignup.png"));
        butSignup.setIcon(Pic);
    }//GEN-LAST:event_butSignupMouseEntered

    private void butSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butSignupMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButSignup.png"));
        butSignup.setIcon(Pic);
    }//GEN-LAST:event_butSignupMouseExited

    private void butLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butLogoutMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butLogout.png"));
        butLogout.setIcon(Pic);
    }//GEN-LAST:event_butLogoutMouseEntered

    private void butLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butLogoutMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButLogout.png"));
        butLogout.setIcon(Pic);
    }//GEN-LAST:event_butLogoutMouseExited

    private void butLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLogoutActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Do you want to Logout?", "LOGOUT", JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.YES_OPTION) {
            Formatter outFile = null;
            try {
                outFile = new Formatter(FILE_NAME);
                for (int row = 0; row < showInfomationTable.getRowCount(); row++) {
                    outFile.format("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n",
                            dtm.getValueAt(row, 0),
                            dtm.getValueAt(row, 1),
                            dtm.getValueAt(row, 2),
                            dtm.getValueAt(row, 3),
                            dtm.getValueAt(row, 4),
                            dtm.getValueAt(row, 5),
                            dtm.getValueAt(row, 6),
                            dtm.getValueAt(row, 7),
                            dtm.getValueAt(row, 8),
                            dtm.getValueAt(row, 9));
                }

            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                if (outFile != null) outFile.close();
            }

            HomeGui hgui = new HomeGui();
            hgui.setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_butLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton butAddInfo;
    private javax.swing.JLabel butClose;
    private javax.swing.JPanel butLoginPanel;
    private javax.swing.JButton butLogout;
    private javax.swing.JPanel butLogoutPanel;
    private javax.swing.JLabel butMinimize;
    private javax.swing.JButton butRemove;
    private javax.swing.JButton butShowProducts;
    private javax.swing.JButton butSignin;
    private javax.swing.JButton butSignup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable showInfomationTable;
    private javax.swing.JLabel userLogo;
    private javax.swing.JLabel usernameBG;
    private javax.swing.JLabel usernameShow;
    private javax.swing.JPanel usershowBGPanel;
    private javax.swing.JPanel usershowPanel;
    // End of variables declaration//GEN-END:variables
}
