/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalProject;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author nutkamonphunturat
 */
public class LogGui extends javax.swing.JDialog {

    private Person person;
    public static String inUser;
    public static LogGui SignIn;

    /**
     * Creates new form LogGui
     */
    public LogGui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        this.inUser = inUsername.getText();
        this.SignIn = this;
    }

    public void showAdd() {
        inUsername.setText("");
        inPassword.setText("");
        setVisible(true);
    }

    public Person getPerson() {
        return person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        inUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JLabel();
        inPassword = new javax.swing.JTextField();
        butClose = new javax.swing.JLabel();
        butDone = new javax.swing.JButton();
        butBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/BMR.png"))); // NOI18N
        Logo.setPreferredSize(new java.awt.Dimension(100, 30));

        txtUsername.setFont(new java.awt.Font("FC Friday", 0, 13)); // NOI18N
        txtUsername.setText("Username");

        inUsername.setBackground(new java.awt.Color(238, 243, 246));
        inUsername.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        inUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inUsername.setBorder(null);

        txtPassword.setFont(new java.awt.Font("FC Friday", 0, 13)); // NOI18N
        txtPassword.setText("Password");

        inPassword.setBackground(new java.awt.Color(238, 243, 246));
        inPassword.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        inPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inPassword.setBorder(null);

        butClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButClose.png"))); // NOI18N
        butClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butCloseMouseEntered(evt);
            }
        });

        butDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButDone.png"))); // NOI18N
        butDone.setBorderPainted(false);
        butDone.setContentAreaFilled(false);
        butDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butDoneMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butDoneMouseEntered(evt);
            }
        });
        butDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDoneActionPerformed(evt);
            }
        });

        butBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButBack.png"))); // NOI18N
        butBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butBackMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butBackMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butBackMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butClose))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUsername)
                                .addComponent(inUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPassword)
                                .addComponent(inPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(butDone, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(butClose)
                    .addComponent(butBack))
                .addGap(10, 10, 10)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butDone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_butCloseMouseClicked

    private void butCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButClose.png"));
        butClose.setIcon(Pic);
    }//GEN-LAST:event_butCloseMouseExited

    private void butCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butClose.png"));
        butClose.setIcon(Pic);
    }//GEN-LAST:event_butCloseMouseEntered

    private void butDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDoneActionPerformed

        if (inUsername.getText().equals("")) {
            int result = JOptionPane.showConfirmDialog(this, "Please fill out the infomation!", "ERROR", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                return;
            } else return;
        }
        if (inPassword.getText().equals("")) {
            int result = JOptionPane.showConfirmDialog(this, "Please fill out the infomation!", "ERROR", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                return;
            } else return;
        }
        
        try {
            String Filepath = "/Users/nutkamonphunturat/Documents/PSU/Object Oreinted Programming/OOP/src/FinalProject/TextFile/Registation.txt";
            String username = inUsername.getText();
            String password = inPassword.getText();
    
    
            FileReader fr = new FileReader(Filepath);
            BufferedReader br = new BufferedReader(fr);
            String line, user, pass;
            boolean isLoginSuccess = false;
            while ((line = br.readLine()) != null) {
                user = line.split(",")[0].toLowerCase();
                pass = line.split(",")[1].toLowerCase();
                if (user.equals(username) && pass.equals(password)) {
                    isLoginSuccess = true;

                    person = new Person(inUsername.getText(), inPassword.getText());
                    this.dispose();
                    HomeGui.AddInfo.setEnabled(true);
                    HomeGui.ShowProducts.setEnabled(true);
                    HomeGui.Home.setVisible(true);
                    HomeGui.BG.setVisible(true);
                    HomeGui.butLogOut.setVisible(true);
                    HomeGui.SignIn.setVisible(false);
                    HomeGui.SignUp.setVisible(false);
                    HomeGui.UserLogo.setVisible(true);
                    
                    break;
                } 
           }
                
                
            if (!isLoginSuccess) {
                int result = JOptionPane.showConfirmDialog(this, "Username or Password wrong!", " ", JOptionPane.OK_CANCEL_OPTION);
                if (result == JOptionPane.OK_OPTION) {
                    inUsername.setText("");
                    inPassword.setText("");
                    return;
                }
            }
            fr.close();
         
            
    }catch(Exception e){
    e.printStackTrace();
        }
    }//GEN-LAST:event_butDoneActionPerformed

    private void butBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butBackMouseClicked
        this.dispose();
        HomeGui.Home.setVisible(true);
    }//GEN-LAST:event_butBackMouseClicked

    private void butBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butBackMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButBack.png"));
        butBack.setIcon(Pic);
    }//GEN-LAST:event_butBackMouseExited

    private void butBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butBackMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butBack.png"));
        butBack.setIcon(Pic);
    }//GEN-LAST:event_butBackMouseEntered

    private void butDoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butDoneMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butDone.png"));
        butDone.setIcon(Pic);
    }//GEN-LAST:event_butDoneMouseEntered

    private void butDoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butDoneMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButDone.png"));
        butDone.setIcon(Pic);
    }//GEN-LAST:event_butDoneMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogGui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogGui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogGui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogGui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LogGui dialog = new LogGui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel butBack;
    private javax.swing.JLabel butClose;
    private javax.swing.JButton butDone;
    private javax.swing.JTextField inPassword;
    private javax.swing.JTextField inUsername;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
