/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalProject;

import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author nutkamonphunturat
 */
public class OrderComplete extends javax.swing.JDialog {

    public static OrderComplete oC;
    public static JLabel oPrice;
    
    /**
     * Creates new form OrderComplete
     */
    public OrderComplete(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        this.oC = this;
        this.oPrice = textPrice;
        
        LocalDate myTime = LocalDate.now();
        String myFormatTime = myTime.format(DateTimeFormatter.ofPattern("dd-MM-yy"));
        
        textName.setText(HomeGui.Home.Name);
        textPrice.setText(Double.toString(showCart.sC.total));
        textDate.setText(myFormatTime);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtThank = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        butClose = new javax.swing.JLabel();
        nameShowPanel = new javax.swing.JPanel();
        textName = new javax.swing.JLabel();
        nameShowBGPanel = new javax.swing.JPanel();
        nameBG = new javax.swing.JLabel();
        priceShowPanel = new javax.swing.JPanel();
        textPrice = new javax.swing.JLabel();
        priceShowBGPanel = new javax.swing.JPanel();
        priceBG = new javax.swing.JLabel();
        dateShowPanel = new javax.swing.JPanel();
        textDate = new javax.swing.JLabel();
        dateShowBGPanel = new javax.swing.JPanel();
        dateBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        txtThank.setFont(new java.awt.Font("FC Friday", 0, 24)); // NOI18N
        txtThank.setForeground(new java.awt.Color(55, 73, 87));
        txtThank.setText("THANK FOR ORDER");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/BMR.png"))); // NOI18N

        txtUsername.setFont(new java.awt.Font("FC Friday", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(55, 73, 87));
        txtUsername.setText("Username");

        txtPrice.setFont(new java.awt.Font("FC Friday", 0, 14)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(55, 73, 87));
        txtPrice.setText("Price");

        txtDate.setFont(new java.awt.Font("FC Friday", 0, 14)); // NOI18N
        txtDate.setForeground(new java.awt.Color(55, 73, 87));
        txtDate.setText("Date");

        butClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButClose.png"))); // NOI18N
        butClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butCloseMouseEntered(evt);
            }
        });

        nameShowPanel.setOpaque(false);
        nameShowPanel.setPreferredSize(new java.awt.Dimension(84, 16));
        nameShowPanel.setLayout(null);

        textName.setBackground(new java.awt.Color(255, 255, 255));
        textName.setFont(new java.awt.Font("FC Friday", 0, 14)); // NOI18N
        textName.setForeground(new java.awt.Color(255, 255, 255));
        textName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textName.setToolTipText("");
        textName.setPreferredSize(new java.awt.Dimension(84, 16));
        nameShowPanel.add(textName);
        textName.setBounds(3, 0, 80, 16);

        nameShowBGPanel.setOpaque(false);
        nameShowBGPanel.setPreferredSize(new java.awt.Dimension(84, 16));

        nameBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blueeBG.png"))); // NOI18N

        javax.swing.GroupLayout nameShowBGPanelLayout = new javax.swing.GroupLayout(nameShowBGPanel);
        nameShowBGPanel.setLayout(nameShowBGPanelLayout);
        nameShowBGPanelLayout.setHorizontalGroup(
            nameShowBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameBG)
        );
        nameShowBGPanelLayout.setVerticalGroup(
            nameShowBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameBG)
        );

        nameShowPanel.add(nameShowBGPanel);
        nameShowBGPanel.setBounds(0, 0, 84, 16);

        priceShowPanel.setOpaque(false);
        priceShowPanel.setPreferredSize(new java.awt.Dimension(84, 16));
        priceShowPanel.setSize(new java.awt.Dimension(84, 16));
        priceShowPanel.setLayout(null);

        textPrice.setBackground(new java.awt.Color(255, 255, 255));
        textPrice.setFont(new java.awt.Font("FC Friday", 0, 14)); // NOI18N
        textPrice.setForeground(new java.awt.Color(255, 255, 255));
        textPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textPrice.setToolTipText("");
        textPrice.setPreferredSize(new java.awt.Dimension(84, 16));
        priceShowPanel.add(textPrice);
        textPrice.setBounds(3, 0, 80, 16);

        priceShowBGPanel.setOpaque(false);
        priceShowBGPanel.setPreferredSize(new java.awt.Dimension(84, 16));

        priceBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blueeBG.png"))); // NOI18N
        priceBG.setSize(new java.awt.Dimension(84, 16));

        javax.swing.GroupLayout priceShowBGPanelLayout = new javax.swing.GroupLayout(priceShowBGPanel);
        priceShowBGPanel.setLayout(priceShowBGPanelLayout);
        priceShowBGPanelLayout.setHorizontalGroup(
            priceShowBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(priceBG)
        );
        priceShowBGPanelLayout.setVerticalGroup(
            priceShowBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(priceBG)
        );

        priceShowPanel.add(priceShowBGPanel);
        priceShowBGPanel.setBounds(0, 0, 110, 16);

        dateShowPanel.setOpaque(false);
        dateShowPanel.setPreferredSize(new java.awt.Dimension(84, 16));
        dateShowPanel.setSize(new java.awt.Dimension(84, 16));
        dateShowPanel.setLayout(null);

        textDate.setBackground(new java.awt.Color(255, 255, 255));
        textDate.setFont(new java.awt.Font("FC Friday", 0, 14)); // NOI18N
        textDate.setForeground(new java.awt.Color(255, 255, 255));
        textDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textDate.setToolTipText("");
        textDate.setPreferredSize(new java.awt.Dimension(83, 16));
        dateShowPanel.add(textDate);
        textDate.setBounds(3, 0, 80, 16);

        dateShowBGPanel.setOpaque(false);
        dateShowBGPanel.setPreferredSize(new java.awt.Dimension(84, 16));
        dateShowBGPanel.setSize(new java.awt.Dimension(84, 16));

        dateBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blueeBG.png"))); // NOI18N

        javax.swing.GroupLayout dateShowBGPanelLayout = new javax.swing.GroupLayout(dateShowBGPanel);
        dateShowBGPanel.setLayout(dateShowBGPanelLayout);
        dateShowBGPanelLayout.setHorizontalGroup(
            dateShowBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dateBG)
        );
        dateShowBGPanelLayout.setVerticalGroup(
            dateShowBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dateBG)
        );

        dateShowPanel.add(dateShowBGPanel);
        dateShowBGPanel.setBounds(0, 0, 84, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(butClose)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(txtThank))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUsername)
                                        .addComponent(txtPrice))
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nameShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(priceShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtDate)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                    .addComponent(dateShowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(logo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(butClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtThank)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsername)
                            .addComponent(nameShowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(txtPrice))
                    .addComponent(priceShowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDate)
                    .addComponent(dateShowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_butCloseMouseClicked

    private void butCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButClose.png"));
        butClose.setIcon(Pic);
    }//GEN-LAST:event_butCloseMouseExited

    private void butCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butClose.png"));
        butClose.setIcon(Pic);
    }//GEN-LAST:event_butCloseMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OrderComplete dialog = new OrderComplete(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel butClose;
    private javax.swing.JLabel dateBG;
    private javax.swing.JPanel dateShowBGPanel;
    private javax.swing.JPanel dateShowPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nameBG;
    private javax.swing.JPanel nameShowBGPanel;
    private javax.swing.JPanel nameShowPanel;
    private javax.swing.JLabel priceBG;
    private javax.swing.JPanel priceShowBGPanel;
    private javax.swing.JPanel priceShowPanel;
    private javax.swing.JLabel textDate;
    private javax.swing.JLabel textName;
    private javax.swing.JLabel textPrice;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtThank;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
