/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalProject;

import static FinalProject.myCart.cart;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author nutkamonphunturat
 */
public class showProduct extends javax.swing.JDialog {

    public static showProduct sP;
    public static JLabel usernameShow;
    public static String Price;
    
    /**
     * Creates new form showProduct
     */
    public showProduct(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.sP = this;
        
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        showProductTable.getTableHeader().setOpaque(false);
        showProductTable.getTableHeader().setBackground(Color.decode("#7C9FB3"));
        showUser.setText(HomeGui.Name);
        
        String FilePath = "/Users/nutkamonphunturat/Documents/PSU/Object Oreinted Programming/OOP/src/FinalProject/TextFile/Product List.txt";
        File file = new File(FilePath);
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)showProductTable.getModel();
            model.setColumnIdentifiers(columnsName);
            
            Object[] tableLines = br.lines().toArray();
            
            for(int i = 0; i < tableLines.length; i++){
                String Line = tableLines[i].toString().trim();
                String[] dataRow = Line.split(",");
                model.addRow(dataRow);
            }
        } 
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        butClose = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        showProductTable = new javax.swing.JTable();
        butShowCart = new javax.swing.JButton();
        butBackHome = new javax.swing.JButton();
        usernameLogo = new javax.swing.JLabel();
        usernamePanel = new javax.swing.JPanel();
        showUser = new javax.swing.JLabel();
        usernameBGPanel = new javax.swing.JPanel();
        usernameBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/BMR.png"))); // NOI18N

        butClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButClose.png"))); // NOI18N
        butClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butCloseMouseEntered(evt);
            }
        });

        showProductTable.setBackground(new java.awt.Color(238, 243, 246));
        showProductTable.setFont(new java.awt.Font("FC Friday", 0, 11)); // NOI18N
        showProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        showProductTable.setGridColor(new java.awt.Color(238, 243, 246));
        showProductTable.setSelectionBackground(new java.awt.Color(125, 160, 182));
        showProductTable.setShowGrid(false);
        showProductTable.setShowHorizontalLines(true);
        showProductTable.setShowVerticalLines(true);
        showProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showProductTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(showProductTable);

        butShowCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankCart24px.png"))); // NOI18N
        butShowCart.setBorderPainted(false);
        butShowCart.setContentAreaFilled(false);
        butShowCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butShowCartMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butShowCartMouseEntered(evt);
            }
        });
        butShowCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butShowCartActionPerformed(evt);
            }
        });

        butBackHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankHome24px.png"))); // NOI18N
        butBackHome.setBorderPainted(false);
        butBackHome.setContentAreaFilled(false);
        butBackHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butBackHomeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butBackHomeMouseEntered(evt);
            }
        });
        butBackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBackHomeActionPerformed(evt);
            }
        });

        usernameLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/user16px.png"))); // NOI18N

        usernamePanel.setOpaque(false);
        usernamePanel.setPreferredSize(new java.awt.Dimension(94, 16));
        usernamePanel.setLayout(null);

        showUser.setBackground(new java.awt.Color(255, 255, 255));
        showUser.setFont(new java.awt.Font("FC Friday", 0, 14)); // NOI18N
        showUser.setForeground(new java.awt.Color(123, 160, 183));
        showUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showUser.setToolTipText("");
        showUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        showUser.setPreferredSize(new java.awt.Dimension(94, 16));
        usernamePanel.add(showUser);
        showUser.setBounds(3, 0, 90, 16);

        usernameBGPanel.setOpaque(false);
        usernameBGPanel.setPreferredSize(new java.awt.Dimension(94, 16));

        usernameBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/showBG.png"))); // NOI18N

        javax.swing.GroupLayout usernameBGPanelLayout = new javax.swing.GroupLayout(usernameBGPanel);
        usernameBGPanel.setLayout(usernameBGPanelLayout);
        usernameBGPanelLayout.setHorizontalGroup(
            usernameBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernameBG)
        );
        usernameBGPanelLayout.setVerticalGroup(
            usernameBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernameBG)
        );

        usernamePanel.add(usernameBGPanel);
        usernameBGPanel.setBounds(0, 0, 94, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameLogo))
                    .addComponent(butClose)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butBackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butShowCart, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(butClose)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logo)
                    .addComponent(butShowCart)
                    .addComponent(butBackHome))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLogo))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_butCloseMouseClicked

    private void butCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButClose.png"));
        butClose.setIcon(Pic);
    }//GEN-LAST:event_butCloseMouseExited

    private void butCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butClose.png"));
        butClose.setIcon(Pic);
    }//GEN-LAST:event_butCloseMouseEntered

    private void butShowCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butShowCartActionPerformed
        showCart sc = new showCart(HomeGui.Home, true);
        sc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butShowCartActionPerformed

    private void butShowCartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butShowCartMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/cart24px.png"));
        butShowCart.setIcon(Pic);
    }//GEN-LAST:event_butShowCartMouseEntered

    private void butShowCartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butShowCartMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankCart24px.png"));
        butShowCart.setIcon(Pic);
    }//GEN-LAST:event_butShowCartMouseExited

    private void butBackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBackHomeActionPerformed
        HomeGui.Home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butBackHomeActionPerformed

    private void butBackHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butBackHomeMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/home24px.png"));
        butBackHome.setIcon(Pic);
    }//GEN-LAST:event_butBackHomeMouseEntered

    private void butBackHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butBackHomeMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankHome24px.png"));
        butBackHome.setIcon(Pic);
    }//GEN-LAST:event_butBackHomeMouseExited

    private void showProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showProductTableMouseClicked
        int index = showProductTable.getSelectedRow();
        TableModel model = showProductTable.getModel();
        
        String product = model.getValueAt(index ,0).toString();
        String protein = model.getValueAt(index, 1).toString();
        String carbohydrate = model.getValueAt(index, 2).toString();
        String calories = model.getValueAt(index, 3).toString();
        String type = model.getValueAt(index, 4).toString();
        double price = Double.parseDouble(model.getValueAt(index, 5).toString());

        
        int result = JOptionPane.showConfirmDialog(this, 
                                                   "Do you want to add " + product + " ?", 
                                                   "BMR Shop",
                                                   JOptionPane.YES_NO_OPTION,
                                                   JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
                Food food = new Food(product ,protein, carbohydrate, calories, type, price);
                cart.addProduct(food);   
                Price = Double.toString(price);
        }
    }//GEN-LAST:event_showProductTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                showProduct dialog = new showProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton butBackHome;
    private javax.swing.JLabel butClose;
    private javax.swing.JButton butShowCart;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable showProductTable;
    private javax.swing.JLabel showUser;
    private javax.swing.JLabel usernameBG;
    private javax.swing.JPanel usernameBGPanel;
    private javax.swing.JLabel usernameLogo;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables
}
