/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalProject;

import static FinalProject.myCart.cart;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Formatter;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author nutkamonphunturat
 */
public class showCart extends javax.swing.JDialog {

    private static final String FILE_NAME = "/Users/nutkamonphunturat/Documents/PSU/Object Oreinted Programming/OOP/src/FinalProject/TextFile/Product Ordering.txt";
    private DefaultTableModel dtm;
    public static showCart sC;
    public String Total;
    public double total = 0;

    /**
     * Creates new form showCart
     */
    public showCart(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        this.sC = this;

        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) showCartTable.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);

        File file = new File(FILE_NAME);
        if (!file.exists()) {
            return;
        }

        dtm = (DefaultTableModel) showCartTable.getModel();
        for (Product item : cart.getProduct()) {
            dtm.insertRow(0, new String[]{
                item.getProduct(), item.getProtein(), item.getCarbohydrate(),
                item.getCalories(), item.getType(), String.valueOf(item.getPrice())
            });
            total += item.getPrice();
        }

        Total = Double.toString(total);
        textTotal.setText(Total);

        showCartTable.setAutoCreateRowSorter(true);
        showCartTable.getRowSorter().toggleSortOrder(0);

        showCartTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                boolean selected = showCartTable.getSelectedRow() != -1;
                butRemove.setEnabled(selected);
            }
        });
    }

    public int toModelRow(int viewRow) {
        return showCartTable.getRowSorter().convertRowIndexToModel(viewRow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        butClose = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        showCartTable = new javax.swing.JTable();
        butConfirm = new javax.swing.JButton();
        butMoreCart = new javax.swing.JButton();
        totalLogo = new javax.swing.JLabel();
        totalShowPanel = new javax.swing.JPanel();
        textTotal = new javax.swing.JLabel();
        totalShowBGPanel = new javax.swing.JPanel();
        totalBG = new javax.swing.JLabel();
        butRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/BMR.png"))); // NOI18N

        butClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButClose.png"))); // NOI18N
        butClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butCloseMouseEntered(evt);
            }
        });

        showCartTable.setBackground(new java.awt.Color(238, 243, 246));
        showCartTable.setFont(new java.awt.Font("FC Friday", 0, 11)); // NOI18N
        showCartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proudct", "Protein", "Carbohydrate", "Calories", "Type", "Price"
            }
        ));
        showCartTable.setGridColor(new java.awt.Color(238, 243, 246));
        showCartTable.setSelectionBackground(new java.awt.Color(125, 160, 182));
        jScrollPane2.setViewportView(showCartTable);

        butConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankConfirmCart.png"))); // NOI18N
        butConfirm.setBorderPainted(false);
        butConfirm.setContentAreaFilled(false);
        butConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butConfirmMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butConfirmMouseEntered(evt);
            }
        });
        butConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConfirmActionPerformed(evt);
            }
        });

        butMoreCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankMoreCart.png"))); // NOI18N
        butMoreCart.setBorderPainted(false);
        butMoreCart.setContentAreaFilled(false);
        butMoreCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butMoreCartMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butMoreCartMouseEntered(evt);
            }
        });
        butMoreCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMoreCartActionPerformed(evt);
            }
        });

        totalLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/money16px.png"))); // NOI18N

        totalShowPanel.setOpaque(false);
        totalShowPanel.setPreferredSize(new java.awt.Dimension(94, 16));
        totalShowPanel.setLayout(null);

        textTotal.setBackground(new java.awt.Color(255, 255, 255));
        textTotal.setFont(new java.awt.Font("FC Friday", 0, 14)); // NOI18N
        textTotal.setForeground(new java.awt.Color(123, 160, 183));
        textTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTotal.setToolTipText("");
        textTotal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        textTotal.setPreferredSize(new java.awt.Dimension(94, 16));
        totalShowPanel.add(textTotal);
        textTotal.setBounds(3, 0, 90, 16);

        totalShowBGPanel.setOpaque(false);
        totalShowBGPanel.setPreferredSize(new java.awt.Dimension(94, 16));

        totalBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/showBG.png"))); // NOI18N

        javax.swing.GroupLayout totalShowBGPanelLayout = new javax.swing.GroupLayout(totalShowBGPanel);
        totalShowBGPanel.setLayout(totalShowBGPanelLayout);
        totalShowBGPanelLayout.setHorizontalGroup(
            totalShowBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalBG)
        );
        totalShowBGPanelLayout.setVerticalGroup(
            totalShowBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalBG)
        );

        totalShowPanel.add(totalShowBGPanel);
        totalShowBGPanel.setBounds(0, 0, 94, 16);

        butRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/icon/blankButRemove.png"))); // NOI18N
        butRemove.setBorderPainted(false);
        butRemove.setContentAreaFilled(false);
        butRemove.setEnabled(false);
        butRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butRemoveMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butRemoveMouseEntered(evt);
            }
        });
        butRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butMoreCart, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalShowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(butClose)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(butClose)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logo)
                    .addComponent(butConfirm)
                    .addComponent(butMoreCart))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalShowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLogo)
                    .addComponent(butRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_butCloseMouseClicked

    private void butCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButClose.png"));
        butClose.setIcon(Pic);
    }//GEN-LAST:event_butCloseMouseExited

    private void butCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butClose.png"));
        butClose.setIcon(Pic);
    }//GEN-LAST:event_butCloseMouseEntered

    private void butConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butConfirmMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankConfirmCart.png"));
        butConfirm.setIcon(Pic);
    }//GEN-LAST:event_butConfirmMouseExited

    private void butConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butConfirmMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/confirm24px.png"));
        butConfirm.setIcon(Pic);
    }//GEN-LAST:event_butConfirmMouseEntered

    private void butConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConfirmActionPerformed
        Formatter outFile = null;
        LocalDate myTime = LocalDate.now();
        String myFormatTime = myTime.format(DateTimeFormatter.ofPattern("dd-MM-yy"));

        try {
            FileWriter writer = new FileWriter(FILE_NAME, true);
            BufferedWriter buffered = new BufferedWriter(writer);
            for (int row = 0; row < showCartTable.getRowCount(); row++) {
                    buffered.write(myFormatTime + "," + HomeGui.Name + "," + dtm.getValueAt(row, 0) + "," + dtm.getValueAt(row, 1) + "," + dtm.getValueAt(row, 2) + "," 
                            + dtm.getValueAt(row, 3) + "," + dtm.getValueAt(row, 4) + "," + dtm.getValueAt(row, 5) + "\n");
                    buffered.flush();
            }
            buffered.close();

        } catch (Exception e) {
            e.printStackTrace();
            return;
        } finally {
            if (outFile != null) {
                outFile.close();
            }
        }

        this.dispose();
        OrderComplete oc = new OrderComplete(HomeGui.Home, true);
        oc.setVisible(true);
    }//GEN-LAST:event_butConfirmActionPerformed

    private void butMoreCartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butMoreCartMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankMoreCart.png"));
        butMoreCart.setIcon(Pic);
    }//GEN-LAST:event_butMoreCartMouseExited

    private void butMoreCartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butMoreCartMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/more24px.png"));
        butMoreCart.setIcon(Pic);
    }//GEN-LAST:event_butMoreCartMouseEntered

    private void butMoreCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMoreCartActionPerformed
        this.dispose();
        showProduct sp = new showProduct(HomeGui.Home, true);
        sp.setVisible(true);
    }//GEN-LAST:event_butMoreCartActionPerformed

    private void butRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRemoveActionPerformed
        int row = toModelRow(showCartTable.getSelectedRow());
        String dtmprice = (String) dtm.getValueAt(row, 5);
        double getDTMPrice = Double.parseDouble(dtmprice);
        total = total - (int) getDTMPrice;
        textTotal.setText(Double.toString(total));
        dtm.removeRow(row);
    }//GEN-LAST:event_butRemoveActionPerformed

    private void butRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butRemoveMouseEntered
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/butRemove.png"));
        butRemove.setIcon(Pic);
    }//GEN-LAST:event_butRemoveMouseEntered

    private void butRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butRemoveMouseExited
        ImageIcon Pic = new ImageIcon(getClass().getResource("/FinalProject/icon/blankButRemove.png"));
        butRemove.setIcon(Pic);
    }//GEN-LAST:event_butRemoveMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                showCart dialog = new showCart(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel butClose;
    private javax.swing.JButton butConfirm;
    private javax.swing.JButton butMoreCart;
    private javax.swing.JButton butRemove;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable showCartTable;
    private javax.swing.JLabel textTotal;
    private javax.swing.JLabel totalBG;
    private javax.swing.JLabel totalLogo;
    private javax.swing.JPanel totalShowBGPanel;
    private javax.swing.JPanel totalShowPanel;
    // End of variables declaration//GEN-END:variables
}
